using System;
using System.Collections.Generic;
using System.Linq;
using Namespace = Generator.Model.Namespace;

namespace Generator.Renderer.Public;

internal static class FrameworkTypeRegistration
{
    public static string Render(GirModel.Namespace ns)
    {
        return $@"
using System;
using System.Runtime.InteropServices;

namespace {Namespace.GetPublicName(ns)}
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    internal partial class Module
    {{
        static partial void RegisterTypes()
        {{
            {ns.Classes
                .Where(cls => !cls.Fundamental)
                .Select(RenderClass)
                .Join(Environment.NewLine)}

            {ns.Records
                .Where(record => record.TypeFunction is not null)
                .Select(RenderRecord)
                .Join(Environment.NewLine)}

            {ns.Unions
                .Where(union => union.TypeFunction is not null)
                .Select(RenderUnion)
                .Join(Environment.NewLine)}
        }}
    }}
}}";
    }

    private static string RenderClass(GirModel.Class cls)
    {
        return $@"
try
{{
    {RenderPlatformSupportCondition(cls as GirModel.PlatformDependent)}
    GObject.Internal.TypeDictionary.Add(typeof({cls.Name}), new GObject.Type(Internal.{cls.Name}.GetGType()));
}}
catch(Exception e)
{{
    Console.WriteLine($""Could not register class type '{cls.Name}': {{e.Message}}"");
}}";
    }

    private static string RenderRecord(this GirModel.Record record)
    {
        return $@"
try
{{
    GObject.Internal.TypeDictionary.Add(typeof({record.Name}), new GObject.Type(Internal.{record.Name}.GetGType()));
}}
catch(Exception e)
{{
    Console.WriteLine($""Could not register record type '{record.Name}': {{e.Message}}"");
}}";
    }

    private static string RenderUnion(this GirModel.Union union)
    {
        return $@"
try
{{
    GObject.Internal.TypeDictionary.Add(typeof({union.Name}), new GObject.Type(Internal.{union.Name}.GetGType()));
}}
catch(Exception e)
{{
    Console.WriteLine($""Could not register union type '{union.Name}': {{e.Message}}"");
}}";
    }

    private static string RenderPlatformSupportCondition(GirModel.PlatformDependent? platformDependent)
    {
        if (platformDependent is null)
            return string.Empty;

        if (platformDependent.SupportsLinux && platformDependent.SupportsMacos && platformDependent.SupportsWindows)
            return string.Empty; //All platforms supported

        var statements = new List<string>();

        if (platformDependent.SupportsLinux)
            statements.Add("RuntimeInformation.IsOSPlatform(OSPlatform.Linux)");

        if (platformDependent.SupportsMacos)
            statements.Add("RuntimeInformation.IsOSPlatform(OSPlatform.OSX)");

        if (platformDependent.SupportsWindows)
            statements.Add("RuntimeInformation.IsOSPlatform(OSPlatform.Windows)");

        return $"if({string.Join(" || ", statements)})";
    }
}
