using System;
using System.Linq;
using Generator.Model;

namespace Generator.Renderer.Public;

internal static class InterfaceImplementationFunctions
{
    public static string Render(GirModel.Interface @interface)
    {
        return $@"
using System;
using System.Linq;
using GObject;
using System.Runtime.InteropServices;

#nullable enable

namespace {Namespace.GetPublicName(@interface.Namespace)};

// AUTOGENERATED FILE - DO NOT MODIFY

public partial class {Interface.GetImplementationName(@interface)}
{{
    {FunctionRenderer.Render(@interface.TypeFunction)}

    {@interface.Functions
        .Select(FunctionRenderer.Render)
        .Join(Environment.NewLine)}
}}";
    }
}
