using System.Linq;

namespace Generator.Renderer.Public;

public static class InterfaceImplementationFramework
{
    public static string Render(GirModel.Interface @interface)
    {
        return $@"
using System;
using GObject;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace {Model.Namespace.GetPublicName(@interface.Namespace)};

// AUTOGENERATED FILE - DO NOT MODIFY

{PlatformSupportAttribute.Render(@interface as GirModel.PlatformDependent)}
public sealed partial class {Model.Interface.GetImplementationName(@interface)} : {GetParent(@interface)}, {@interface.Name}, GObject.InstanceFactory
{{
    public {Model.Interface.GetImplementationName(@interface)}({GetParentHandle(@interface)} handle) : base(handle)
    {{
    }}

    static object GObject.InstanceFactory.Create(IntPtr ptr, bool ownsHandle)
    {{
        var handle = new {GetParentHandle(@interface)}(ptr);
        var obj = new {Model.Interface.GetImplementationName(@interface)}(handle);
        
//TODO!!
        GObject.Internal.InstanceCache.AddToggleRef(obj);

        return obj;
    }}
}}";
    }

    private static string GetParent(GirModel.Interface @interface)
    {
        var parentPrerequisite = @interface.Prerequisites.FirstOrDefault(x => x is GirModel.Class);

        return parentPrerequisite is null
            ? "GObject.Object"
            : Model.ComplexType.GetFullyQualified(parentPrerequisite);
    }

    private static string GetParentHandle(GirModel.Interface @interface)
    {
        var parentPrerequisite = @interface.Prerequisites
            .OfType<GirModel.Class>()
            .FirstOrDefault();

        return parentPrerequisite is null
            ? "GObject.Internal.ObjectHandle"
            : Model.Class.GetFullyQualifiedInternalHandleName(parentPrerequisite);
    }
}
