using System;
using System.Linq;
using Generator.Model;

namespace Generator.Renderer.Public;

internal static class InterfaceImplementationMethods
{
    public static string Render(GirModel.Interface @interface)
    {
        return $@"
using System;
using System.Linq;
using GObject;
using System.Runtime.InteropServices;

#nullable enable

namespace {Namespace.GetPublicName(@interface.Namespace)};

// AUTOGENERATED FILE - DO NOT MODIFY

public partial class {Interface.GetImplementationName(@interface)}
{{
    {@interface.Methods
        .Where(Method.IsEnabled)
        .Where(method => !method.IsFree())//Freeing is handled by the framework via a IDisposable implementation.
        .Select(MethodRenderer.Render)
        .Join(Environment.NewLine)}
}}";
    }
}
