using Generator.Model;

namespace Generator.Renderer.Public;

public static class InterfaceImplementationFramework
{
    public static string Render(GirModel.Interface @interface)
    {
        return $@"
using System;
using GObject;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace {Namespace.GetPublicName(@interface.Namespace)};

// AUTOGENERATED FILE - DO NOT MODIFY

{PlatformSupportAttribute.Render(@interface as GirModel.PlatformDependent)}
public sealed partial class {Interface.GetImplementationName(@interface)} : GObject.Object, {@interface.Name}, GObject.InstanceFactory
{{
    public {Interface.GetImplementationName(@interface)}(GObject.Internal.ObjectHandle handle) : base(handle)
    {{
    }}

    static object GObject.InstanceFactory.Create(IntPtr handle, bool ownsHandle)
    {{
        return new {Interface.GetImplementationName(@interface)}(new GObject.Internal.ObjectHandle(handle, ownsHandle));
    }}
}}";
    }
}
