using Generator.Model;

namespace Generator.Renderer.Public;

public static class InterfaceImplementationFramework
{
    public static string Render(GirModel.Interface @interface)
    {
        return $@"
using System;
using GObject;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace {Namespace.GetPublicName(@interface.Namespace)};

// AUTOGENERATED FILE - DO NOT MODIFY

{PlatformSupportAttribute.Render(@interface as GirModel.PlatformDependent)}
public sealed partial class {Interface.GetImplementationName(@interface)} : GObject.Object, {@interface.Name}
{{
    public {Interface.GetImplementationName(@interface)}(IntPtr handle, bool ownedRef) : base(handle, ownedRef)
    {{
    }}
}}";
    }
}
