using System;
using System.Linq;
using Generator.Model;

namespace Generator.Renderer.Public;

internal static class InterfaceImplementationSignals
{
    public static string Render(GirModel.Interface @interface)
    {
        return $@"
using System;
using GObject;
using System.Runtime.InteropServices;

#nullable enable

namespace {Namespace.GetPublicName(@interface.Namespace)}
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public partial class {Model.Interface.GetImplementationName(@interface)}
    {{
        {@interface.Signals
            .Select(signal => ClassInterfaceSignal.Render(@interface, signal))
            .Join(Environment.NewLine)}
    }}
}}";
    }
}
