using Generator3.Renderer.Internal;

namespace Generator3.Generation.Record
{
    public class InternalMethodsTemplate : Template<InternalMethodsModel>
    {
        public string Render(InternalMethodsModel model)
        {
            return $@"
using System;
using System.Runtime.InteropServices;

#nullable enable

namespace { model.NamespaceName }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public partial class { model.Name }
    {{
        public partial class Methods
        {{
            {model.TypeFunction.Render()}
            {model.Functions.Render()}
            {model.Methods.Render()}
            {model.Constructors.Render()}
        }}
    }}
}}";
        }
    }
}
