using Generator3.Renderer.Public;

namespace Generator3.Generation.Class.Standard
{
    public class PublicMethodsTemplate : Template<PublicMethodsModel>
    {
        public string Render(PublicMethodsModel model)
        {
            return $@"
using System;
using System.Linq;
using GObject;
using System.Runtime.InteropServices;

#nullable enable

namespace { model.NamespaceName }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public partial class { model.Name }
    {{
        {model.Methods.Render()}
    }}
}}";
        }
    }
}
