using Generator3.Renderer;

namespace Generator3.Generation.Callback
{
    public class PublicAsyncHandlerTemplate : Template<PublicAsyncHandlerModel>
    {
        public string Render(PublicAsyncHandlerModel model)
        {
            return $@"
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace { model.NamespaceName }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    /// <summary>
    /// Async Handler for {model.DelegateType}. An async annotation indicates the closure will
    /// be called precisely once, after which it is then available for garbage collection.
    /// </summary>
    {model.PlatformDependent.RenderPlatformSupportAttributes()}
    public class {model.Name} : IDisposable
    {{
        private {model.DelegateType} managedCallback;
        private GCHandle gch;

        public {model.InternalDelegateType} NativeCallback;
    
        public {model.Name}({model.DelegateType} managed)
        {{
            managedCallback = managed;
            gch = GCHandle.Alloc(this);
            {CommonHandlerRenderUtils.RenderNativeCallback(model)}
        }}
        
        public void Dispose()
        {{
            if (gch.IsAllocated)
                gch.Free();
        }}
    }}
}}";
        }
    }
}
