namespace Generator3.Renderer
{
    public class ConstantsUnit : Renderer<Model.ConstantsUnit>
    {
        public string Render(Model.ConstantsUnit model)
        {
            return $@"
using System;
using System.Runtime.InteropServices;

#nullable enable

namespace { model.NamespaceName }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public partial class Constants
    {{
        {model.Constants.Write(Constant.Get)}
    }}
}}";
        }
    }
}
