namespace Generator3.Renderer
{
    internal class NativeRecordStuctUnit : Renderer<Model.NativeRecordStructUnit>
    {
        public string Render(Model.NativeRecordStructUnit model)
        {
            return $@"
using System;
using System.Runtime.InteropServices;

#nullable enable

namespace { model.NamespaceName }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public partial class { model.Name }
    {{
        [StructLayout(LayoutKind.Sequential)]
        public partial struct Struct
        {{
            {model.Fields.ForEachCall(NativeField.Get)}
        }}
    }}
}}";
        }
    }
}
