using Generator3.Renderer.Internal;

namespace Generator3.Generation.Functions
{
    public class InternalTemplate : Template<InternalModel>
    {
        public string Render(InternalModel model)
        {
            return $@"
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace { model.NamespaceName }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public partial class Functions
    {{
        {model.InternalFunctions.Render()}
    }}
}}";
        }
    }
}
