using Generator3.Renderer.Native;

namespace Generator3.Generation.Functions
{
    public class NativeTemplate : Template<NativeModel>
    {
        public string Render(NativeModel model)
        {
            return $@"
using System;
using System.Runtime.InteropServices;

#nullable enable

namespace { model.NamespaceName }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public partial class Functions
    {{
        {model.NativeFunctions.Render()}
    }}
}}";
        }
    }
}
