namespace Generator3.Generation.Record
{
    public class InternalOwnedHandleTemplate : Template<InternalOwnedHandleModel>
    {
        public string Render(InternalOwnedHandleModel model)
        {
            return $@"
using System;
using System.Runtime.InteropServices;

#nullable enable

namespace { model.InternalNamespaceName }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public partial class {model.OwnedHandleName} : {model.HandleName}
    {{
        private {model.OwnedHandleName}() : base(true) {{ }}

        public {model.OwnedHandleName}(IntPtr handle) : base(true)
        {{
            SetHandle(handle);
        }}

        protected override bool ReleaseHandle()
        {{
            {model.RenderFreeCall()}
        }}

        {model.RenderFreeFunction()}
    }}
}}";
        }
    }
}
