using System;
using System.Linq;
using Generator.Model;

namespace Generator.Renderer.Public;

internal static class ClassSignals
{
    public static string Render(GirModel.Class cls)
    {
        return $@"
using System;
using GObject;
using System.Runtime.InteropServices;

#nullable enable

namespace {Namespace.GetPublicName(cls.Namespace)}
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public partial class {cls.Name}
    {{
        {cls.Signals
            .Select(x => ClassSignal.Render(cls, x))
            .Join(Environment.NewLine)}
    }}

    {cls.Signals
        .Select(RenderArgs)
        .Join(Environment.NewLine)}  

}}"; 
    }

    private static string RenderArgs(GirModel.Signal signal)
    {
        try
        {
            return SignalArgs.Render(signal);   
        }
        catch (Exception ex)
        {
            var message = $"Did not generate signal args '{Signal.GetName(signal)}': {ex.Message}";

            if (ex is NotImplementedException)
                Log.Debug(message);
            else
                Log.Warning(message);

            return string.Empty;
        }
    }
}
