using System;
using System.Linq;
using Generator.Model;

namespace Generator.Renderer.Public;

internal static class ClassSignals
{
    public static string Render(GirModel.Class cls)
    {
        if (cls.Implements.SelectMany(x => x.Signals).Any())
        {
            
        }

        return $@"
using System;
using GObject;
using System.Runtime.InteropServices;

#nullable enable

namespace {Namespace.GetPublicName(cls.Namespace)}
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public partial class {cls.Name}
    {{
        {cls.Signals
            .Select(x => ClassSignal.Render(cls, x))
            .Join(Environment.NewLine)}

        {cls.Implements
            .SelectMany(iface => iface.Signals.Select(signal => ClassSignal.Render(iface, signal)))
            .Join(Environment.NewLine)}
    }}
}}";
    }
}
