using System;
using System.Linq;
using Generator.Model;

namespace Generator.Renderer.Public;

internal static class ClassInterfaceSignals
{
    public static string Render(GirModel.Class cls)
    {
        return $@"
using System;
using GObject;
using System.Runtime.InteropServices;

#nullable enable

namespace {Namespace.GetPublicName(cls.Namespace)}
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public partial class {cls.Name}
    {{
        {cls.Implements
            .SelectMany(iface => iface.Signals.Select(signal => ClassInterfaceSignal.Render(iface, signal)))
            .Join(Environment.NewLine)}
    }}
}}";
    }
}
