using Generator3.Renderer;
using Generator3.Renderer.Public;

namespace Generator3.Generation.Enumeration
{
    public class Template : Template<Model>
    {
        public string Render(Model model)
        {
            return $@"
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace { model.NamespaceName }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    {model.PlatformDependent.RenderPlatformSupportAttributes()}
    public enum { model.Name } : long
    {{
        {model.Members.Render()}
    }}
}}";
        }
    }
}
