using Generator3.Renderer;

namespace Generator3.Generation.Enumeration
{
    public class Template : Template<Model>
    {
        public string Render(Model model)
        {
            return $@"
using System;
using System.Runtime.InteropServices;

#nullable enable

namespace { model.NamespaceName }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public enum { model.Name } : long
    {{
        {model.Members.ForEachCall(Member.Render)}
    }}
}}";
        }
    }
}
