using System.Linq;
using Generator3.Renderer;

namespace Generator3.Generation.Callback
{
    public class NativeTemplate : Template<NativeModel>
    {
        public string Render(NativeModel model)
        {
            return $@"
using System;
using System.Runtime.InteropServices;

#nullable enable

namespace { model.NamespaceName }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public delegate {model.ReturnType.Render()} {model.Name}({model.Parameters.Render()});
}}";
        }
    }
}
