using Generator3.Renderer.Internal;

namespace Generator3.Generation.Record
{
    public class InternalStructTemplate : Template<InternalStructModel>
    {
        public string Render(InternalStructModel model)
        {
            return $@"
using System;
using System.Runtime.InteropServices;

#nullable enable

namespace { model.NamespaceName }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    [StructLayout(LayoutKind.Sequential)]
    public partial struct { model.Name }
    {{
        {model.Fields.Render()}
    }}
}}";
        }
    }
}
