using System.Runtime.CompilerServices;
using GObject;

namespace Gio
{
    internal partial class Module
    {
        [ModuleInitializer]
        internal static void Initialize()
        {
            InitializeDllImport();
            InitializeTypeDictionary();
        }

        static partial void InitializeDllImport();
        
        internal static void InitializeTypeDictionary()
        {
            //TODO: This should be autogenerated
            GObject.Native.TypeDictionary.Add(typeof(DBusConnection), DBusConnection.GTypeDescriptor);
        }
    }
}
