using System.Collections.Generic;
using System.Linq;
using Generator.Model;

namespace Generator.Renderer.Public;

internal static class CallbackDelegate
{
    public static string Render(GirModel.Callback callback)
    {
        return $@"
using System;
using System.Runtime.InteropServices;

#nullable enable

namespace {Namespace.GetPublicName(callback.Namespace)}
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public delegate {ReturnType.Render(callback.ReturnType)} {callback.Name}({RenderParameters(callback.Parameters.Where(p => p.Closure is null or 0))});
}}";
    }

    private static string RenderParameters(IEnumerable<GirModel.Parameter> parameters)
    {
        return parameters
            .Select(RenderParameter)
            .Join(", ");
    }

    private static string RenderParameter(GirModel.Parameter parameter)
    {
        var name = Parameter.GetName(parameter);
        var typeData = RenderableParameterFactory.Create(parameter);

        return $"{typeData.Direction}{typeData.NullableTypeName} {name}";
    }
}
