using System;
using Generator.Model;

namespace Generator.Renderer.Public;

internal static class CallbackDelegate
{
    public static string Render(GirModel.Callback callback)
    {
        try
        {
            return $@"
using System;
using System.Runtime.InteropServices;

#nullable enable

namespace {Namespace.GetPublicName(callback.Namespace)};

// AUTOGENERATED FILE - DO NOT MODIFY

{Callback.Render(callback)}";
        }
        catch (Exception ex)
        {
            Log.Warning($"Did not generate callback delegate {callback.Name}: {ex.Message}");

            return string.Empty;
        }
    }
}
