using Generator.Model;

namespace Generator.Renderer.Internal;

internal static class FrameworkExtensions
{
    public static string Render(GirModel.Namespace ns)
    {
        return $@"
using System;
using System.Runtime.InteropServices;

#nullable enable

namespace {Namespace.GetInternalName(ns)};

// AUTOGENERATED FILE - DO NOT MODIFY

internal static class Extensions
{{
    public static T[] MarshalToStructure<T>(this IntPtr[] array)
    {{
        var data = new T[array.Length];
    
        for(int i = 0; i < array.Length; i++)
            data[i] = Marshal.PtrToStructure<T>(array[i]) ?? throw new System.Exception(""Cant marshal IntPtr[] because one element is not marshallable"");

        return data;
    }}
}}";
    }
}
