using System;
using System.Linq;

namespace Generator3.Rendering.Templates
{
    internal class Constants : Generation.Unit.Constants.Renderer
    {
        public string Render(Generation.Unit.Constants.Model model)
        {
            return $@"
using System;
using System.Runtime.InteropServices;

#nullable enable

namespace { model.NamespaceName }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public partial class Constants
    {{
        {model.Constants.Write(Constant.Get)}
    }}
}}";
        }
    }
}
