using System;
using System.Linq;

namespace Generator3.Rendering.Templates
{
    internal class Enumeration : Generation.Unit.Enumeration.Renderer
    {
        public string Render(Generation.Unit.Enumeration.Model model)
        {
            return $@"
using System;
using System.Runtime.InteropServices;

#nullable enable

namespace { model.NamespaceName }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public enum { model.Name } : long
    {{
        {model.Members.Write(Member.Get)}
    }}
}}";
        }
    }
}
