using Generator3.Generation.Unit.Native.RecordFunctions;

namespace Generator3.Rendering.Templates
{
    internal class NativeRecordFunctions : Generation.Unit.Renderer<Model>
    {
        public string Render(Model model)
        {
            return $@"
using System;
using System.Runtime.InteropServices;

#nullable enable

namespace { model.NamespaceName }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public partial class { model.Name}
    {{
        public partial class Methods
        {{

        }}
    }}
}}";
        }
    }
}
