using Generator3.Generation.Unit.Native.Functions;

namespace Generator3.Rendering.Templates
{
    internal class NativeFunctions : Generation.Unit.Renderer<Model>
    {
        public string Render(Model model)
        {
            return $@"
using System;
using System.Runtime.InteropServices;

#nullable enable

namespace { model.NamespaceName }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public partial class Functions
    {{
        {model.NativeFunctions.Write(NativeFunction.Get)}
    }}
}}";
        }
    }
}
