namespace Generator3.Generation.Union
{
    public class InternalStructTemplate : Template<InternalStructModel>
    {
        public string Render(InternalStructModel model)
        {
            return $@"
using System;
using System.Runtime.InteropServices;

#nullable enable

namespace { model.NamespaceName }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public partial class { model.Name }
    {{
        [StructLayout(LayoutKind.Sequential)]
        public partial struct Struct
        {{
            //TODO Fields
        }}
    }}
}}";
        }
    }
}
