using System;
using System.Linq;
using Generator.Model;

namespace Generator.Renderer.Public;

internal static class EnumerationErrorDomain
{
    public static string Render(GirModel.Enumeration enumeration)
    {
        return $@"
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace {Namespace.GetPublicName(enumeration.Namespace)};

// AUTOGENERATED FILE - DO NOT MODIFY

/// <summary>
/// Contains all error codes of the {enumeration.Name} error-domain.
/// </summary>
{PlatformSupportAttribute.Render(enumeration as GirModel.PlatformDependent)}
[StructLayout(LayoutKind.Explicit)]
public readonly ref struct {enumeration.Name}
{{
    private static readonly global::GLib.Quark Domain = GetDomainQuark();

    [FieldOffset(0)]
    private readonly int _errorCode; 

    /// <summary>
    /// Creates a new error in the {enumeration.Name} domain with a given error code.
    /// </summary>
    /// <param name=""errorCode"">A specific error code of the domain</param>
    public {enumeration.Name}(int errorCode)
    {{
        _errorCode = errorCode;
    }}

    /// <summary>
    /// Converts a {enumeration.Name} into a <see cref=""GLib.ErrorCode""/> which can be used to match a <see cref=""GLib.GException""/>.
    /// </summary>
    public static implicit operator global::GLib.ErrorCode({enumeration.Name} e) => new()
    {{
        Domain = Domain,
        Code = e._errorCode
    }};

    /// <summary>
    /// Can be used to match a <see cref=""GLib.GException""/> with any error code of the ""{enumeration.Name}"" error-domain.
    /// </summary>
    public static GLib.Quark Any => Domain;

    {enumeration
        .Members
        .Select(x => Render(enumeration.Name, x))
        .Join(Environment.NewLine)}

    [DllImport(global::{Namespace.GetInternalName(enumeration.Namespace)}.ImportResolver.Library, EntryPoint = ""{enumeration.ErrorDomain!.Replace('-', '_')}"")]
    private static extern uint GetDomainQuark();
}}";
    }

    private static string Render(string enumerationName, GirModel.Member member)
    {
        var memberName = Member.GetName(member);
        return $$"""
               /// <summary>
               /// Can be used to match a <see cref="GLib.GException"/> with the "{{memberName}}" code ({{member.Value}}).
               /// </summary>
               public static {{enumerationName}} {{memberName}} => new({{member.Value}});
               """;
    }
}
