using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Generator.Model;

namespace Generator.Renderer.Public;

internal static class GlobalFunctions
{
    public static string Render(IEnumerable<GirModel.Function> functions)
    {
        return $@"
using System;
using System.Linq;

#nullable enable

namespace {Namespace.GetPublicName(functions.First().Namespace)};

// AUTOGENERATED FILE - DO NOT MODIFY

public static partial class Functions
{{
    {functions
        .Select(FunctionRenderer.Render)
        .Join(Environment.NewLine)}
}}";
    }
}
