using System;
using System.Linq;
using Generator.Model;

namespace Generator.Renderer.Public;

internal static class Interface
{
    public static string Render(GirModel.Interface iface)
    {
        return $$"""
                 using System;
                 using GObject;
                 using System.Runtime.InteropServices;

                 #nullable enable

                 namespace {{Namespace.GetPublicName(iface.Namespace)}};

                 // AUTOGENERATED FILE - DO NOT MODIFY

                 public partial interface {{iface.Name}} : GObject.NativeObject, GObject.GTypeProvider, IDisposable
                 {
                     static GObject.Type GObject.GTypeProvider.GetGType()
                     {
                         return Internal.{{iface.Name}}.GetGType();
                     }

                     {{iface.RenderProperties()}}
                     {{iface.RenderSignals()}}
                         
                     {{iface.Signals
                         .Select(SignalArgs.Render)
                         .Join(Environment.NewLine)}}
                         
                     {{iface.RenderMethods()}}
                 }
                 """;
    }
}
