using System;
using System.Linq;
using Generator.Model;

namespace Generator.Renderer.Public;

internal static class InterfaceEvents
{
    public static string Render(GirModel.Interface iface)
    {
        return $$"""

                 using System;
                 using GObject;
                 using System.Runtime.InteropServices;

                 #nullable enable

                 namespace {{Namespace.GetPublicName(iface.Namespace)}};

                 // AUTOGENERATED FILE - DO NOT MODIFY

                 public partial interface {{iface.Name}}
                 {
                     {{iface.Signals
                         .Select(x => RenderEvent(iface, x))
                         .Join(Environment.NewLine)}}
                 }
                 """;
    }

    private static string RenderEvent(GirModel.Interface iface, GirModel.Signal signal)
    {
        return $"public event {Signal.GetDelegateName(signal, iface)} {Signal.GetName(signal)};";
    }

}
