using Generator.Model;

namespace Generator.Renderer.Public;

internal static class InterfaceMethods
{
    public static string Render(GirModel.Interface iface)
    {
        return $@"
using System;
using GObject;
using System.Runtime.InteropServices;

#nullable enable

namespace {Namespace.GetPublicName(iface.Namespace)}
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public partial interface {iface.Name}
    {{
        //TODO implement interface
    }}
}}";
    }
}
