namespace Generator3.Generation.Record
{
    public class InternalSafeHandleTemplate : Template<InternalSafeHandleModel>
    {
        public string Render(InternalSafeHandleModel model)
        {
            return $@"
using System;
using System.Runtime.InteropServices;

#nullable enable

namespace { model.NamespaceName }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public partial class { model.Name }
    {{
        public class {model.HandleClassName} : SafeHandle
        {{
            public static {model.HandleClassName} Null = new {model.HandleClassName}();
    
            protected {model.HandleClassName}() : base(IntPtr.Zero, true) {{}}
            public {model.HandleClassName}(IntPtr handle) : base(IntPtr.Zero, true)
            {{
                SetHandle(handle);
            }}
    
            public sealed override bool IsInvalid => handle == IntPtr.Zero;
    
            protected override bool ReleaseHandle()
            {{
                //TODO: Release memory
                throw new NotImplementedException();
            }}
        }}
    }}
}}";
        }
    }
}
