using Generator3.Renderer;

namespace Generator3.Generation.Record
{
    public class NativeFunctionsTemplate : Template<NativeFunctionsModel>
    {
        public string Render(NativeFunctionsModel model)
        {
            return $@"
using System;
using System.Runtime.InteropServices;

#nullable enable

namespace { model.NamespaceName }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public partial class { model.Name }
    {{
        public partial class Methods
        {{
            {model.TypeFunction.IfNotNullCall(NativeFunction.Render)}
            {model.Functions.ForEachCall(NativeFunction.Render)}
        }}
    }}
}}";
        }
    }
}
