<Project Sdk="Microsoft.NET.Sdk">  
  <PropertyGroup>
    <RootNamespace>GirLoader</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StrongInject" Version="1.4.4" />
    <PackageReference Include="OneOf" Version="3.0.271" />
    
    <ProjectReference Include="..\GirModel\GirModel.csproj" />
  </ItemGroup>
</Project>
