namespace Generator3.Renderer
{
    internal class BitfieldUnit : Renderer<Model.BitfieldUnit>
    {
        public string Render(Model.BitfieldUnit model)
        {
            return $@"
using System;
using System.Runtime.InteropServices;

#nullable enable

namespace { model.NamespaceName }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    [Flags]
    public enum { model.Name } : ulong
    {{
        {model.Members.ForEachCall(Member.Render)}
    }}
}}";
        }
    }
}
