namespace Generator3.Renderer
{
    internal class EnumerationUnit : Renderer<Model.EnumerationUnit>
    {
        public string Render(Model.EnumerationUnit model)
        {
            return $@"
using System;
using System.Runtime.InteropServices;

#nullable enable

namespace { model.NamespaceName }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public enum { model.Name } : long
    {{
        {model.Members.ForEachCall(Member.Render)}
    }}
}}";
        }
    }
}
