namespace Generator3.Renderer
{
    internal class NativeFunctionsUnit : Renderer<Model.NativeFunctionsUnit>
    {
        public string Render(Model.NativeFunctionsUnit model)
        {
            return $@"
using System;
using System.Runtime.InteropServices;

#nullable enable

namespace { model.NamespaceName }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public partial class Functions
    {{
        {model.NativeFunctions.ForEachCall(NativeFunction.Render)}
    }}
}}";
        }
    }
}
