using System;
using System.Runtime.InteropServices;

#nullable enable

namespace GLib.Native
{
    // AUTOGENERATED FILE - DO NOT MODIFY
    public partial class String
    {
        public partial class Methods
        {
            public static void Free(IntPtr str)
                => Free(str, true);
        }
    }
}
