using System;

#nullable enable

namespace GLib.Native
{
    // AUTOGENERATED FILE - DO NOT MODIFY
    public partial class ThreadPool
    {

    #region Methods
        
        public partial class Methods
        {
            public static void Free(IntPtr pool)
                => Free(pool, true, true); //TODO clarify which parameters are usefull
        }
        #endregion
    }
}
