namespace Generator3.Generation.Framework
{
    public class NativeExtensionsTemplate : Template<NativeExtensionsModel>
    {
        public string Render(NativeExtensionsModel model)
        {
            return $@"
using System;
using System.Runtime.InteropServices;

#nullable enable

namespace {model.NamespaceName}
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public static class Extensions
    {{
        public static T[] MarshalToStructure<T>(this IntPtr[] array)
        {{
            var data = new T[array.Length];
        
            for(int i = 0; i < array.Length; i++)
                data[i] = Marshal.PtrToStructure<T>(array[i]) ?? throw new Exception(""Cant marshal IntPtr[] because one element is not marshallable"");

            return data;
        }}
    }}
}}";
        }
    }
}
