using System;
using System.Linq;
using Generator.Model;

namespace Generator.Renderer.Public;

internal static class ClassConstructors
{
    public static string Render(GirModel.Class cls)
    {
        var newKeyWord = Class.IsGObjectObject(cls) ? string.Empty : "new ";
        
        return $$"""
                 using System;
                 using System.Linq;
                 using GObject;
                 using System.Runtime.InteropServices;

                 #nullable enable

                 namespace {{Namespace.GetPublicName(cls.Namespace)}};

                 // AUTOGENERATED FILE - DO NOT MODIFY

                 public partial class {{cls.Name}}
                 {
                     /// <summary>
                     /// Creates a new {{cls.Name}} and sets the properties specified by the construct arguments.
                     /// </summary>
                     /// <param name="constructArguments">The properties to set.</param>
                     public static {{newKeyWord}}{{cls.Name}} NewWithProperties(GObject.ConstructArgument[] constructArguments)
                     {
                         var ptr = GObject.Internal.Object.NewWithProperties(GetGType(), constructArguments);
                         return CreateInstance(ptr);
                     }

                     {{cls.Constructors
                         .Select(ConstructorRenderer.Render)
                         .Join(Environment.NewLine)}}
                         
                     private static {{cls.Name}} CreateInstance(IntPtr ptr)
                     {
                        var handle = new {{Class.GetFullyQualifiedInternalHandleName(cls)}}(ptr);
                        var obj = new {{cls.Name}}(handle);
                 
                        GObject.Internal.InstanceCache.AddToggleRef(obj);
                        {{RenderUnref(cls)}}
                 
                        return obj;
                     }
                 }
                 """;
    }
    
    private static string RenderUnref(GirModel.Class cls)
    {
        /*
         * - Regular objects can be unrefed because there was an additional toggle ref added so one valid ref remains
         * - Initially unowned objects have a floating reference which must be taken and then removed
         */
        
        return Class.IsInitiallyUnowned(cls)
            ? """
              GObject.Internal.Object.TakeRef(ptr);
              GObject.Internal.Object.Unref(ptr);
              """
            : "GObject.Internal.Object.Unref(ptr);";
    }
}
