using System;
using System.Linq;
using Generator.Model;

namespace Generator.Renderer.Public;

internal static class ClassInterfaceMethods
{
    public static string Render(GirModel.Class cls)
    {
        return $@"
using System;
using System.Linq;
using GObject;
using System.Runtime.InteropServices;

#nullable enable

namespace {Namespace.GetPublicName(cls.Namespace)};

// AUTOGENERATED FILE - DO NOT MODIFY

public partial class {cls.Name}
{{
    {cls.Implements
        .Select(RenderInterfaceMethods)
        .Join(Environment.NewLine)}
}}";
    }

    private static string RenderInterfaceMethods(GirModel.Interface @interface)
    {
        return @interface.Methods
            .Where(Method.IsEnabled)
            .Select(MethodRenderer.Render)
            .Join(Environment.NewLine);
    }
}
