using Generator.Model;

namespace Generator.Renderer.Internal;

internal static class InterfaceMethods
{
    public static string Render(GirModel.Interface iface)
    {
        return $@"
using System;
using GObject;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace {Namespace.GetInternalName(iface.Namespace)}
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    {PlatformSupportAttribute.Render(iface as GirModel.PlatformDependent)}
    public partial class {iface.Name}
    {{
        {Functions.Render(iface.TypeFunction)}
        {Functions.Render(iface.Functions)}
        {Methods.Render(iface.Methods)}
    }}
}}";
    }
}
