using System.Linq;
using Generator.Model;

namespace Generator.Renderer.Internal;

internal static class OpaqueUntypedRecordHandle
{
    public static string Render(GirModel.Record record)
    {
        if (!record.Functions.Any() && !record.Methods.Any())
            return EmptyHandle(record);

        return StandardHandle(record);
    }

    private static string EmptyHandle(GirModel.Record record)
    {
        var typeName = Model.OpaqueUntypedRecord.GetInternalHandle(record);
        var unownedHandleTypeName = Model.OpaqueUntypedRecord.GetInternalUnownedHandle(record);
        var ownedHandleTypeName = Model.OpaqueUntypedRecord.GetInternalOwnedHandle(record);

        return $@"using System;
using GObject;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace {Namespace.GetInternalName(record.Namespace)};

// AUTOGENERATED FILE - DO NOT MODIFY

{PlatformSupportAttribute.Render(record as GirModel.PlatformDependent)}
public abstract class {typeName} : SafeHandle
{{
    public sealed override bool IsInvalid => handle == IntPtr.Zero;

    protected {typeName}(bool ownsHandle) : base(IntPtr.Zero, ownsHandle) {{ }}

    public {ownedHandleTypeName} OwnedCopy() => throw new NotSupportedException(""Can't create a copy of this handle"");
    public {unownedHandleTypeName} UnownedCopy() => throw new NotSupportedException(""Can't create a copy of this handle"");
}}

public class {unownedHandleTypeName} : {typeName}
{{
    private static {unownedHandleTypeName}? nullHandle;
    public static {unownedHandleTypeName} NullHandle => nullHandle ??= new {unownedHandleTypeName}();

    /// <summary>
    /// Creates a new instance of {unownedHandleTypeName}. Used automatically by PInvoke.
    /// </summary>
    internal {unownedHandleTypeName}() : base(false) {{ }}

    /// <summary>
    /// Creates a new instance of {unownedHandleTypeName}. Assumes that the given pointer is unowned by the runtime.
    /// </summary>
    public {unownedHandleTypeName}(IntPtr ptr) : base(false)
    {{
        SetHandle(ptr);
    }}

    protected override bool ReleaseHandle()
    {{
        throw new Exception(""UnownedHandle must not be freed"");
    }}
}}

public class {ownedHandleTypeName} : {typeName}
{{
    /// <summary>
    /// Creates a new instance of {ownedHandleTypeName}. Used automatically by PInvoke.
    /// </summary>
    internal {ownedHandleTypeName}() : base(true) {{ }}

    /// <summary>
    /// Creates a new instance of {ownedHandleTypeName}. Assumes that the given pointer is owned by the runtime.
    /// </summary>
    public {ownedHandleTypeName}(IntPtr ptr) : base(true)
    {{
        SetHandle(ptr);
    }}

    /// <summary>
    /// Create a {ownedHandleTypeName} from a pointer that is assumed unowned.
    /// </summary>
    /// <param name=""ptr"">A pointer to a {record.Name} which is not owned by the runtime.</param>
    /// <returns>A {ownedHandleTypeName}</returns>
    public static {ownedHandleTypeName} FromUnowned(IntPtr ptr) => throw new NotSupportedException(""Can't create a copy of this handle"");

    protected override bool ReleaseHandle() => throw new NotSupportedException(""Can't free this handle"");
}}";
    }

    private static string StandardHandle(GirModel.Record record)
    {
        var typeName = Model.OpaqueUntypedRecord.GetInternalHandle(record);
        var unownedHandleTypeName = Model.OpaqueUntypedRecord.GetInternalUnownedHandle(record);
        var ownedHandleTypeName = Model.OpaqueUntypedRecord.GetInternalOwnedHandle(record);

        return $@"using System;
using GObject;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace {Namespace.GetInternalName(record.Namespace)};

// AUTOGENERATED FILE - DO NOT MODIFY

{PlatformSupportAttribute.Render(record as GirModel.PlatformDependent)}
public abstract partial class {typeName} : SafeHandle
{{
    public sealed override bool IsInvalid => handle == IntPtr.Zero;

    protected {typeName}(bool ownsHandle) : base(IntPtr.Zero, ownsHandle) {{ }}

    public partial {ownedHandleTypeName} OwnedCopy();
    public partial {unownedHandleTypeName} UnownedCopy();
}}

public class {unownedHandleTypeName} : {typeName}
{{
    private static {unownedHandleTypeName}? nullHandle;
    public static {unownedHandleTypeName} NullHandle => nullHandle ??= new {unownedHandleTypeName}();

    /// <summary>
    /// Creates a new instance of {unownedHandleTypeName}. Used automatically by PInvoke.
    /// </summary>
    internal {unownedHandleTypeName}() : base(false) {{ }}

    /// <summary>
    /// Creates a new instance of {unownedHandleTypeName}. Assumes that the given pointer is unowned by the runtime.
    /// </summary>
    public {unownedHandleTypeName}(IntPtr ptr) : base(false)
    {{
        SetHandle(ptr);
    }}

    protected override bool ReleaseHandle()
    {{
        throw new Exception(""UnownedHandle must not be freed"");
    }}
}}

public partial class {ownedHandleTypeName} : {typeName}
{{
    /// <summary>
    /// Creates a new instance of {ownedHandleTypeName}. Used automatically by PInvoke.
    /// </summary>
    internal {ownedHandleTypeName}() : base(true) {{ }}

    /// <summary>
    /// Creates a new instance of {ownedHandleTypeName}. Assumes that the given pointer is owned by the runtime.
    /// </summary>
    public {ownedHandleTypeName}(IntPtr ptr) : base(true)
    {{
        SetHandle(ptr);
    }}

    /// <summary>
    /// Create a {ownedHandleTypeName} from a pointer that is assumed unowned.
    /// </summary>
    /// <param name=""ptr"">A pointer to a {record.Name} which is not owned by the runtime.</param>
    /// <returns>A {ownedHandleTypeName}</returns>
    public static partial {ownedHandleTypeName} FromUnowned(IntPtr ptr);

    protected override partial bool ReleaseHandle();
}}";
    }
}
