using Generator.Model;

namespace Generator.Renderer.Internal;

internal static class OpaqueTypedRecord
{
    public static string Render(GirModel.Record record)
    {
        return $@"
using System;
using GObject;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace {Namespace.GetInternalName(record.Namespace)};

// AUTOGENERATED FILE - DO NOT MODIFY

{PlatformSupportAttribute.Render(record as GirModel.PlatformDependent)}
public partial class {record.Name} {RenderNativeGTypeProvider(record)}
{{
    {Constructors.Render(record.Constructors)}
    {Functions.Render(record.TypeFunction)}
    {Functions.Render(record.Functions)}
    {Methods.Render(record.Methods)}
}}";
    }

    private static string RenderNativeGTypeProvider(GirModel.Record record)
    {
        return record.TypeFunction is not null
            ? ": GLib.Internal.NativeGTypeProvider"
            : string.Empty;
    }
}
