using Generator.Model;

namespace Generator.Renderer.Internal;

internal static class UnionMethods
{
    public static string Render(GirModel.Union union)
    {
        return $@"
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace {Namespace.GetInternalName(union.Namespace)}
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    {PlatformSupportAttribute.Render(union as GirModel.PlatformDependent)}
    public partial class {union.Name}
    {{
        {Functions.Render(union.TypeFunction)}
        {Functions.Render(union.Functions)}
        {Methods.Render(union.Methods)}
        {Constructors.Render(union.Constructors)}
    }}
}}";
    }
}
