using Generator3.Renderer.Native;

namespace Generator3.Generation.Class.Standard
{
    public class NativeStructTemplate : Template<NativeStructModel>
    {
        public string Render(NativeStructModel model)
        {
            return $@"
using System;
using System.Runtime.InteropServices;

#nullable enable

namespace { model.NamespaceName }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public partial class { model.Name }
    {{
        public partial class Instance
        {{
            [StructLayout(LayoutKind.Sequential)]
            public partial struct Struct
            {{
                {model.Fields.Render()}
            }}
        }}
    }}
}}";
        }
    }
}
