using System;
using System.Runtime.InteropServices;

#nullable enable

namespace GLib
{
    // AUTOGENERATED FILE - DO NOT MODIFY
    public partial record String
    {

        public partial class Native
        {
            #region Methods
            public partial class Methods
            {
                public static void Free(StringSafeHandle str)
                    => Free(str, true);
            }
            #endregion
        }
    }
}
