namespace Generator3.Generation.Record
{
    public class InternalHandleTemplate : Template<InternalHandleModel>
    {
        public string Render(InternalHandleModel model)
        {
            return $@"
using System;
using System.Runtime.InteropServices;

#nullable enable

namespace { model.InternalNamespaceName }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public partial class { model.Name } : SafeHandle
    {{
        public static {model.Name} Null = new {model.Name}();

        protected {model.Name}() : base(IntPtr.Zero, true) {{}}
        public {model.Name}(IntPtr handle, bool ownsHandle) : base(IntPtr.Zero, ownsHandle)
        {{
            SetHandle(handle);
        }}

        public sealed override bool IsInvalid => handle == IntPtr.Zero;

        protected override bool ReleaseHandle()
        {{
            {model.RenderFreeCall()}
        }}

        {model.RenderFreeFunction()}
    }}
}}";
        }
    }
}
