using Generator3.Renderer;

namespace Generator3.Generation.Record
{
    public class NativeDelegatesTemplate : Template<NativeDelegatesModel>
    {
        public string Render(NativeDelegatesModel model)
        {
            return $@"
using System;
using System.Runtime.InteropServices;

#nullable enable

namespace { model.NamespaceName }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public partial class { model.Name }
    {{
        {model.Callbacks.Render()}
    }}
}}";
        }
    }
}
