using System;
using Generator.Model;

namespace Generator.Renderer.Internal;

internal static class CallbackDelegate
{
    public static string Render(GirModel.Callback callback)
    {
        try
        {
            return $@"
using System;
using System.Runtime.InteropServices;

#nullable enable

namespace {Namespace.GetInternalName(callback.Namespace)}
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public delegate {ReturnTypeRendererCallback.Render(callback.ReturnType)} {callback.Name}({CallbackParameters.Render(callback.Parameters)}{Error.RenderCallback(callback)});
}}";
        }
        catch (Exception ex)
        {
            Log.Warning($"Did not generate callback delegate '{callback.Name}': {ex.Message}");

            return string.Empty;
        }
    }
}
