using Generator3.Renderer;

namespace Generator3.Generation.Class.Fundamental
{
    public class PublicFrameworkTemplate : Template<PublicFrameworkModel>
    {
        public string Render(PublicFrameworkModel model)
        {
            return $@"
using System;
using GObject;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace { model.NamespaceName }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    {model.PlatformDependent.RenderPlatformSupportAttributes()}
    public partial class { model.Name } {model.RenderInheritance()}
    {{
        public {model.Name}(IntPtr handle) : base(handle) {{ }}
    }}
}}";
        }
    }
}
