using System;
using GObject;

namespace Gtk
{
    // AUTOGENERATED FILE - DO NOT MODIFY
    
    public partial class Bin : Container
    {
        private static readonly TypeDescriptor GTypeDescriptor = TypeDescriptor.For("GtkBin", Sys.Bin.get_type);
        
        #region Constructors
        protected internal Bin(IntPtr ptr) : base(ptr) {}
        protected internal Bin(params ConstructParameter[] properties) : base(properties) {}
        #endregion Constructors
    }
}
