using System;
using GObject;

namespace Gtk
{
    // AUTOGENERATED CLASS - DO NOT MODIFY

    [Wrapper("GtkButton")]
    public partial class Button : Bin
    {
        // Type Function
        internal new static GObject.Type GetGType() => new GObject.Type(Sys.Button.get_type());

        // Constructors
        protected Button(IntPtr ptr) : base(ptr) {}
        protected Button(ConstructProp[] properties) : base(properties) {}

        // Properties
    }
}