using System;
using GObject;

namespace Gtk
{
    // AUTOGENERATED CLASS - DO NOT MODIFY

    [Wrapper("GtkButton")]
    public partial class Button : Bin
    {
        // Type Function
        protected internal new static GObject.Type GetGType() => new GObject.Type(Sys.Button.get_type());

        // Constructors
        protected internal Button(IntPtr ptr) : base(ptr) { }
        protected internal Button(params ConstructProp[] properties) : base(properties) { }

        // Properties
    }
}