using System;
using GObject;

namespace Gtk
{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public partial class Button : Bin
    {
        private static readonly TypeDescriptor GTypeDescriptor = TypeDescriptor.For("GtkButton", Sys.Button.get_type);

        #region Constructors
        protected internal Button(IntPtr ptr) : base(ptr) { }
        protected internal Button(params ConstructParam[] properties) : base(properties) { }
        #endregion Constructors
    }
}
