using System;
using GObject;

namespace Gtk
{
    // AUTOGENERATED FILE - DO NOT MODIFY

    [Wrapper("GtkContainer")]
    public partial class Container : Widget
    {
        protected internal new static GObject.Type GetGType() => new GObject.Type(Sys.Container.get_type());

        #region Constructors
        protected internal Container(IntPtr ptr) : base(ptr) { }
        protected internal Container(params ConstructProp[] properties) : base(properties) { }
        #endregion Constructors
    }
}