using System;
using GObject;

namespace Gtk
{
    // AUTOGENERATED FILE - DO NOT MODIFY
    
    public partial class Container : Widget
    {
        private static readonly TypeDescriptor GTypeDescriptor = TypeDescriptor.For("GtkContainer", Sys.Container.get_type);
        
        #region Constructors
        protected internal Container(IntPtr ptr) : base(ptr) {}
        protected internal Container(params ConstructProp[] properties) : base(properties) {}
        #endregion Constructors
    }
}