using System;
using GObject;

namespace Gtk
{
    // AUTOGENERATED FILE - DO NOT MODIFY

    [Wrapper("GtkWidget")]
    public partial class Widget : GObject.InitiallyUnowned
    {
        protected internal new static GObject.Type GetGType() => new GObject.Type(Sys.Widget.get_type());

        #region Constructors
        protected internal Widget(IntPtr ptr) : base(ptr) { }
        protected internal Widget(params ConstructProp[] properties) : base(properties) { }
        #endregion Constructors
    }
}