using System;
using GObject;

namespace Gtk
{
    // AUTOGENERATED FILE - DO NOT MODIFY
    
    public partial class Widget : GObject.InitiallyUnowned
    {
        private static readonly TypeDescriptor GTypeDescriptor = TypeDescriptor.For("GtkWidget", Sys.Widget.get_type);
        
        #region Constructors
        protected internal Widget(IntPtr ptr) : base(ptr) {}
        protected internal Widget(params ConstructParameter[] properties) : base(properties) {}
        #endregion Constructors
    }
}
