using System;
using GObject;

namespace Gtk
{
    // AUTOGENERATED FILE - DO NOT MODIFY

    [Wrapper("GtkWindow")]
    public partial class Window : Bin
    {
        protected internal new static GObject.Type GetGType() => new GObject.Type(Sys.Window.get_type());

        #region Constructors
        protected internal Window(IntPtr ptr) : base(ptr) { }
        protected internal Window(params ConstructProp[] properties) : base(properties) { }
        #endregion Constructors
    }
}