using System;
using GObject;

namespace Gtk
{
    // AUTOGENERATED FILE - DO NOT MODIFY
    
    public partial class Window : Bin
    {
        protected new static readonly TypeDescriptor GTypeDescriptor = TypeDescriptor.For("GtkWindow", Sys.Window.get_type);
        
        #region Constructors
        protected internal Window(IntPtr ptr) : base(ptr) {}
        protected internal Window(params ConstructProp[] properties) : base(properties) {}
        #endregion Constructors
    }
}