#pragma once

// Simple C library to test the generated bindings.
#include "girtest-alias-tester.h"
#include "girtest-bitfield-tester.h"
#include "girtest-byte-array-tester.h"
#include "girtest-callback-tester.h"
#include "girtest-class-tester.h"
#include "girtest-constant-tester.h"
#include "girtest-enum-tester.h"
#include "girtest-error-tester.h"
#include "girtest-integer-array-tester.h"
#include "girtest-long-tester.h"
#include "girtest-opaque-typed-record-tester.h"
#include "girtest-opaque-untyped-record-tester.h"
#include "girtest-platform-string-array-null-terminated-tester.h"
#include "girtest-primitive-value-type-tester.h"
#include "girtest-property-tester.h"
#include "girtest-rename-to-tester.h"
#include "girtest-returning-signal-tester.h"
#include "girtest-signal-tester.h"
#include "girtest-string-array-tester.h"
#include "girtest-string-tester.h"
#include "girtest-typed-record-tester.h"
#include "girtest-untyped-record-tester.h"
#include "girtest-utf8-string-array-null-terminated-tester.h"
#include "data/girtest-executor.h"
#include "data/girtest-executor-impl.h"
