using Generator3.Renderer;

namespace Generator3.Generation.Interface
{
    public class PublicFrameworkTemplate : Template<PublicFrameworkModel>
    {
        public string Render(PublicFrameworkModel model)
        {
            return $@"
using System;
using GObject;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace { model.NamespaceName }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    {model.PlatformDependent.RenderPlatformSupportAttributes()}
    public partial interface { model.Name } : GLib.IHandle
    {{
        IntPtr GLib.IHandle.Handle
        {{
            get
            {{
                System.Diagnostics.Debug.Assert(
                    condition: GetType().IsAssignableTo(typeof(GObject.Object)),
                    message: $""Interface '{{nameof({model.Name})}}' can only be implemented on GObject-based classes""
                );

                return ((GObject.Object)this).Handle;
            }}
        }}
    }}
}}";
        }
    }
}
