using Generator3.Renderer;
using Generator3.Renderer.Internal;

namespace Generator3.Generation.Class.Standard
{
    public class InternalStructTemplate : Template<InternalStructModel>
    {
        public string Render(InternalStructModel model)
        {
            return $@"
using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

#nullable enable

namespace { model.NamespaceName }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    {model.PlatformDependent.RenderPlatformSupportAttributes()}
    [StructLayout(LayoutKind.Sequential)]
    public partial struct { model.Name }
    {{
        {model.Fields.Render()}
    }}
}}";
        }
    }
}
