using Generator3.Renderer;

namespace Generator3.Generation.Constants
{
    public class Template : Template<Model>
    {
        public string Render(Model model)
        {
            return $@"
using System;
using System.Runtime.InteropServices;

#nullable enable

namespace { model.NamespaceName }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public partial class Constants
    {{
        {model.Constants.ForEachCall(Constant.Render)}
    }}
}}";
        }
    }
}
