namespace Generator3.Generation.Class.Standard
{
    public class PublicFrameworkTemplate : Template<PublicFrameworkModel>
    {
        public string Render(PublicFrameworkModel model)
        {
            return $@"
using System;
using GObject;
using System.Runtime.InteropServices;

#nullable enable

namespace { model.NamespaceName }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public partial class { model.Name } {model.RenderInheritance()}
    {{
        {model.RenderParentConstructors()}
    }}
}}";
        }
    }
}
