using System.Runtime.CompilerServices;
using GObject.Native;

namespace GObject
{
    internal partial class Module
    {
        [ModuleInitializer]
        internal static void Initialize()
        {
            InitializeDllImport();
            InitializeTypeDictionary();
        }

        static partial void InitializeDllImport();

        internal static void InitializeTypeDictionary()
        {
            //TODO: This should be autogenerated
            TypeDictionary.Add(typeof(Binding), Binding.GTypeDescriptor);
        }
    }
}
