namespace Gtk
{
    public interface IBox : Orientable
    {
        
    }
    public partial class Box : IBox
    {
        #region Constructors
        
        public Box(Orientation orientation, int spacing) : this(Native.@new(orientation, spacing)) { }
        
        #endregion
        
        #region Methods
        
        //TODO: This would be autogenerated
        public Orientable AsOrientable() => this;

        public void PackStart(Widget widget, bool expand, bool fill, uint padding) 
            => Native.pack_start(Handle, GetHandle(widget), expand, fill, padding);

        #endregion
    }
}
