using Generator3.Renderer.Native;

namespace Generator3.Generation.Callback
{
    public class NativeDelegateTemplate : Template<NativeDelegateModel>
    {
        public string Render(NativeDelegateModel delegateModel)
        {
            return $@"
using System;
using System.Runtime.InteropServices;

#nullable enable

namespace { delegateModel.NamespaceName }
{{
    // AUTOGENERATED FILE - DO NOT MODIFY

    public delegate {delegateModel.ReturnType.Render()} {delegateModel.Name}({delegateModel.Parameters.Render()});
}}";
        }
    }
}
